### ISSUE TITLE
double scrollbar and weird scrolling behaviour

### ISSUE THREAD

**Issue by fucha-co** [fucha-co/ns#2]
i'm not sure what i've done but there are now 2 vertical scrollbars showing (in Edge) and really weird scrolling issues happening too where the content is disappearing and there's almost infinite scroll (in Chrome/Brave)

i'm not certain when this started but i feel like it was right around when i added a TailwindUI component to the Footer.astro component

![image](https://github.com/fucha-co/ns/assets/1171169/03e82238-0ec7-42ae-8e5e-231c18fc641e)

**Comment by shivjm** [comment]
Interestingly, Firefox (on Windows, at least) is fine. Let’s see what the Chrome issue is.
